# Generated by Django 5.2 on 2025-06-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_order_date_order_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='services_2',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
