# Generated by Django 5.2 on 2025-06-03 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_services_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='services_2',
            new_name='services_22',
        ),
    ]
