# Generated by Django 5.2.1 on 2025-06-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_order_options_order_status_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='orders', to='core.service'),
        ),
    ]
