# Generated by Django 5.2.1 on 2025-06-17 08:08

from django.db import migrations

def update_master_names(apps, schema_editor):
    Master = apps.get_model('core', 'Master')
    
    # Обновляем имена для существующих мастеров
    # Предполагаем, что у вас есть 2 мастера с ID 1 и 2
    masters_data = [
        {'id': 1, 'first_name': 'Александр', 'last_name': 'Бородач'},
        {'id': 2, 'first_name': 'Алефтина', 'last_name': 'Кудрявцева'},
        # Добавьте остальных мастеров, если они есть
    ]
    
    for data in masters_data:
        try:
            master = Master.objects.get(id=data['id'])
            master.first_name = data['first_name']
            master.last_name = data['last_name']
            master.save()
        except Master.DoesNotExist:
            pass

def reverse_func(apps, schema_editor):
    # Код для отката изменений, если нужно
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_services'),  # Укажите последнюю миграцию
    ]

    operations = [
        migrations.RunPython(update_master_names, reverse_func),
    ]
