# Generated by Django 5.2.1 on 2025-06-17 08:21

from django.db import migrations
from decimal import Decimal

def update_services_data(apps, schema_editor):
    Service = apps.get_model('core', 'Service')
    
    # Обновляем данные для существующих услуг
    services_data = [
        {
            'id': 1, 
            'name': 'Услуга 1', 
            'price': Decimal('1000.00'),
            'description': 'Описание услуги 1',
            'duration': 60,
            'is_popular': True
        },
        {
            'id': 2, 
            'name': 'Услуга 2', 
            'price': Decimal('2000.00'),
            'description': 'Описание услуги 2',
            'duration': 90,
            'is_popular': False
        },
        {
            'id': 3, 
            'name': 'Полировка лысых', 
            'price': Decimal('1000.00'),
            'description': 'Профессиональная полировка лысины до блеска',
            'duration': 45,
            'is_popular': True
        },
        # Добавьте остальные услуги, если они есть
    ]
    
    for data in services_data:
        try:
            service = Service.objects.get(id=data['id'])
            for key, value in data.items():
                setattr(service, key, value)
            service.save()
        except Service.DoesNotExist:
            Service.objects.create(**data)

def reverse_func(apps, schema_editor):
    # Код для отката изменений, если нужно
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_services'),  # Укажите последнюю миграцию
    ]

    operations = [
        migrations.RunPython(update_services_data, reverse_func),
    ]