# Generated by Django 5.2.1 on 2025-06-17 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20250617_1408'),
        ('core', '0011_auto_20250617_1421'),
    ]

    operations = [
    ]
