# Generated by Django 5.2.1 on 2025-06-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_0010_auto_20250617_1408_0011_auto_20250617_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='first_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='master',
            name='phone',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название услуги'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client_name', 'phone', 'comment'], name='client_phone_comment_idx'),
        ),
    ]
