# Generated by Django 5.2.1 on 2025-06-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_master_first_name_alter_master_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количестов просмотров'),
        ),
    ]
