# Generated by Django 5.2.1 on 2025-06-19 08:23

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_review_date_created'),  # Убедитесь, что это имя последней миграции
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            PRAGMA foreign_keys=off;
            
            -- Создаем временную таблицу с правильной структурой
            CREATE TABLE core_review_new (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                client_name VARCHAR(100) NOT NULL,
                text TEXT NOT NULL,
                rating INTEGER NOT NULL,
                date_created DATETIME NOT NULL,
                master_id INTEGER NOT NULL REFERENCES core_master(id)
            );
            
            -- Копируем данные из старой таблицы во временную
            -- Если date_created отсутствует, используем текущее время
            INSERT INTO core_review_new (id, client_name, text, rating, date_created, master_id)
            SELECT id, client_name, text, rating, CURRENT_TIMESTAMP, master_id FROM core_review;
            
            -- Удаляем старую таблицу
            DROP TABLE core_review;
            
            -- Переименовываем временную таблицу
            ALTER TABLE core_review_new RENAME TO core_review;
            
            -- Создаем индекс для поля date_created
            CREATE INDEX core_review_date_created_idx ON core_review(date_created);
            
            PRAGMA foreign_keys=on;
            """,
            reverse_sql=""  # Обратная операция не требуется
        ),
    ]
