# Generated by Django 5.2.1 on 2025-06-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_master_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.PositiveIntegerField(default=20, help_text='Время в минутах', verbose_name='Время выполнения услуги'),
        ),
    ]
